### PR TITLE
locales

### PR DESCRIPTION
**Pull request by thisisreza**

### CODE REVIEW

**Comment by gueroJeff** [comment]
Hey @thisisreza ,

Thank you for the time you've spent on this. Reviewing the PR, I saw a few things that we likely need to account for in this first PR:

1) Metadata. The metadata is the key to creating en-xx bitext corpora. As the files stand now, if I went to align the he.csv with the en.csv, I would have a very difficult time identifying which 'en' articles have corresponding 'he' translations. I suggest the first commit should consist of xx.csv files that contain the article headers, like the one below:

`"model": "wiki.document",
  "pk": 963,
  "fields": {
    "title": "\u05e0\u05d9\u05d4\u05d5\u05dc \u05e2\u05d5\u05d2\u05d9\u05d5\u05ea",
    "slug": "\u05e0\u05d9\u05d4\u05d5\u05dc \u05e2\u05d5\u05d2\u05d9\u05d5\u05ea",
    "is_template": false,
    "is_localizable": false,
    "locale": "he",
    "current_revision": 983,
    "latest_localizable_revision": null,
    "parent": 670,
    "html": "`  

2) File naming. I plan to incorporate more data from other sources in these directories. If we could designate these files as "sumo" files in their names, that would be really helpful. I'll do the same for "mdn" and "pontoon" data.

3) Empty files. I like the idea to create files for every locale, whether we have data for it or not. Some locales (like af.csv) have unnecessary content when they should likely remain empty.

What are your thoughts?

**Comment by thisisreza** [comment]
Hello @gueroJeff 
Sure.

1- I can add this part to the data
2- So, Do you need an extra name like _sumo_fa.xx?
3- Yes, there might be some, let me think about this and how to solve it.

**Comment by flodolo** [comment]
Passing by question: why is the locale code repeated inside files (not just the empty ones)? You can see it already in the `ak` file, for example.

P.S. locales, not locals ;-)

**Comment by gueroJeff** [comment]
> Passing by question: why is the locale code repeated inside files (not just the empty ones)? You can see it already in the `ak` file, for example.
> 
> P.S. locales, not locals ;-)

Good point, that a redundancy we can avoid.

**Comment by thisisreza** [comment]
> Passing by question: why is the locale code repeated inside files (not just the empty ones)? You can see it already in the `ak` file, for example.
> 
> P.S. locales, not locals ;-)

Flod,

Thank you.
I didn't check every individual locale. But, I'll review this.
It's a very unstructured file and it totally makes sense to me filters missed some data or added more data.

**Pull request closed without merging**
